/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 38
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_import = 1,
  anon_sym_as = 2,
  anon_sym_var = 3,
  anon_sym_EQ = 4,
  anon_sym_SEMI = 5,
  anon_sym_and = 6,
  anon_sym_or = 7,
  anon_sym_EQ_EQ = 8,
  anon_sym_BANG_EQ = 9,
  anon_sym_LT = 10,
  anon_sym_LT_EQ = 11,
  anon_sym_EQ_GT = 12,
  anon_sym_GT = 13,
  anon_sym_PLUS = 14,
  anon_sym_DASH = 15,
  anon_sym_STAR = 16,
  anon_sym_SLASH = 17,
  anon_sym_PERCENT = 18,
  anon_sym_not = 19,
  anon_sym_true = 20,
  anon_sym_false = 21,
  anon_sym_nil = 22,
  sym_string = 23,
  sym_number = 24,
  aux_sym_identifier_token1 = 25,
  anon_sym_DOT = 26,
  sym_unix_path_string = 27,
  sym_comment = 28,
  sym_source_file = 29,
  sym_import = 30,
  sym_stmt = 31,
  sym_declaration = 32,
  sym_expr = 33,
  sym_clause = 34,
  sym__clause = 35,
  sym_binary = 36,
  sym_unary = 37,
  sym_primary = 38,
  sym_identifier = 39,
  aux_sym_source_file_repeat1 = 40,
  aux_sym_source_file_repeat2 = 41,
  aux_sym_identifier_repeat1 = 42,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_import] = "import",
  [anon_sym_as] = "as",
  [anon_sym_var] = "var",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_GT] = ">",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_not] = "not",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_nil] = "nil",
  [sym_string] = "string",
  [sym_number] = "number",
  [aux_sym_identifier_token1] = "identifier_token1",
  [anon_sym_DOT] = ".",
  [sym_unix_path_string] = "unix_path_string",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_import] = "import",
  [sym_stmt] = "stmt",
  [sym_declaration] = "declaration",
  [sym_expr] = "expr",
  [sym_clause] = "clause",
  [sym__clause] = "_clause",
  [sym_binary] = "binary",
  [sym_unary] = "unary",
  [sym_primary] = "primary",
  [sym_identifier] = "identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_identifier_repeat1] = "identifier_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_import] = anon_sym_import,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_var] = anon_sym_var,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_nil] = anon_sym_nil,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_unix_path_string] = sym_unix_path_string,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_import] = sym_import,
  [sym_stmt] = sym_stmt,
  [sym_declaration] = sym_declaration,
  [sym_expr] = sym_expr,
  [sym_clause] = sym_clause,
  [sym__clause] = sym__clause,
  [sym_binary] = sym_binary,
  [sym_unary] = sym_unary,
  [sym_primary] = sym_primary,
  [sym_identifier] = sym_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_identifier_repeat1] = aux_sym_identifier_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_var] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_nil] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_unix_path_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_clause] = {
    .visible = true,
    .named = true,
  },
  [sym__clause] = {
    .visible = false,
    .named = true,
  },
  [sym_binary] = {
    .visible = true,
    .named = true,
  },
  [sym_unary] = {
    .visible = true,
    .named = true,
  },
  [sym_primary] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_left = 1,
  field_op = 2,
  field_right = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_left] = "left",
  [field_op] = "op",
  [field_right] = "right",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_left, 0},
    {field_op, 1},
    {field_right, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '!', 4,
        '"', 1,
        '#', 61,
        '%', 50,
        '*', 48,
        '+', 46,
        '-', 47,
        '.', 59,
        '/', 49,
        ';', 37,
        '<', 42,
        '=', 36,
        '>', 45,
        'a', 16,
        'f', 6,
        'i', 14,
        'n', 11,
        'o', 19,
        't', 20,
        'v', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(28);
      if (lookahead == '#') ADVANCE(61);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(41);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(52);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(53);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(13);
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 14:
      if (lookahead == 'm') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 'n') ADVANCE(8);
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 17:
      if (lookahead == 'o') ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(39);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(34);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(51);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 28:
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(3);
      END_STATE();
    case 29:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '!', 4,
        '"', 1,
        '#', 61,
        '%', 50,
        '*', 48,
        '+', 46,
        '-', 47,
        '/', 49,
        ';', 37,
        '<', 42,
        '=', 5,
        '>', 45,
        'a', 15,
        'f', 6,
        'i', 14,
        'n', 11,
        'o', 19,
        't', 20,
        'v', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(29);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 30:
      if (eof) ADVANCE(31);
      ADVANCE_MAP(
        '"', 1,
        '#', 61,
        '-', 47,
        '.', 59,
        '=', 35,
        'f', 6,
        'i', 14,
        'n', 11,
        't', 20,
        'v', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_var);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(40);
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_nil);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_unix_path_string);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(61);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 29},
  [2] = {.lex_state = 29},
  [3] = {.lex_state = 29},
  [4] = {.lex_state = 29},
  [5] = {.lex_state = 29},
  [6] = {.lex_state = 29},
  [7] = {.lex_state = 29},
  [8] = {.lex_state = 29},
  [9] = {.lex_state = 29},
  [10] = {.lex_state = 29},
  [11] = {.lex_state = 29},
  [12] = {.lex_state = 29},
  [13] = {.lex_state = 29},
  [14] = {.lex_state = 30},
  [15] = {.lex_state = 30},
  [16] = {.lex_state = 30},
  [17] = {.lex_state = 29},
  [18] = {.lex_state = 29},
  [19] = {.lex_state = 30},
  [20] = {.lex_state = 29},
  [21] = {.lex_state = 29},
  [22] = {.lex_state = 29},
  [23] = {.lex_state = 29},
  [24] = {.lex_state = 29},
  [25] = {.lex_state = 29},
  [26] = {.lex_state = 29},
  [27] = {.lex_state = 29},
  [28] = {.lex_state = 29},
  [29] = {.lex_state = 29},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 30},
  [37] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_var] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_nil] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_unix_path_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(33),
    [sym_import] = STATE(10),
    [sym_stmt] = STATE(11),
    [sym_declaration] = STATE(28),
    [sym_expr] = STATE(28),
    [sym_clause] = STATE(27),
    [sym__clause] = STATE(5),
    [sym_binary] = STATE(5),
    [sym_unary] = STATE(5),
    [sym_primary] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(10),
    [aux_sym_source_file_repeat2] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_not] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [anon_sym_nil] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_number] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_var] = ACTIONS(15),
    [anon_sym_SEMI] = ACTIONS(15),
    [anon_sym_and] = ACTIONS(15),
    [anon_sym_or] = ACTIONS(15),
    [anon_sym_EQ_EQ] = ACTIONS(17),
    [anon_sym_BANG_EQ] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(25),
    [anon_sym_PERCENT] = ACTIONS(25),
    [anon_sym_not] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_nil] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_var] = ACTIONS(15),
    [anon_sym_SEMI] = ACTIONS(15),
    [anon_sym_and] = ACTIONS(15),
    [anon_sym_or] = ACTIONS(15),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(25),
    [anon_sym_PERCENT] = ACTIONS(25),
    [anon_sym_not] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_nil] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_var] = ACTIONS(27),
    [anon_sym_SEMI] = ACTIONS(27),
    [anon_sym_and] = ACTIONS(27),
    [anon_sym_or] = ACTIONS(27),
    [anon_sym_EQ_EQ] = ACTIONS(27),
    [anon_sym_BANG_EQ] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(29),
    [anon_sym_LT_EQ] = ACTIONS(27),
    [anon_sym_EQ_GT] = ACTIONS(27),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(27),
    [anon_sym_DASH] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(27),
    [anon_sym_SLASH] = ACTIONS(27),
    [anon_sym_PERCENT] = ACTIONS(27),
    [anon_sym_not] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(27),
    [anon_sym_false] = ACTIONS(27),
    [anon_sym_nil] = ACTIONS(27),
    [sym_string] = ACTIONS(27),
    [sym_number] = ACTIONS(27),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_var] = ACTIONS(31),
    [anon_sym_SEMI] = ACTIONS(31),
    [anon_sym_and] = ACTIONS(33),
    [anon_sym_or] = ACTIONS(33),
    [anon_sym_EQ_EQ] = ACTIONS(17),
    [anon_sym_BANG_EQ] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_LT_EQ] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_GT] = ACTIONS(21),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(25),
    [anon_sym_PERCENT] = ACTIONS(25),
    [anon_sym_not] = ACTIONS(31),
    [anon_sym_true] = ACTIONS(31),
    [anon_sym_false] = ACTIONS(31),
    [anon_sym_nil] = ACTIONS(31),
    [sym_string] = ACTIONS(31),
    [sym_number] = ACTIONS(31),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_var] = ACTIONS(35),
    [anon_sym_SEMI] = ACTIONS(35),
    [anon_sym_and] = ACTIONS(35),
    [anon_sym_or] = ACTIONS(35),
    [anon_sym_EQ_EQ] = ACTIONS(35),
    [anon_sym_BANG_EQ] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(37),
    [anon_sym_LT_EQ] = ACTIONS(35),
    [anon_sym_EQ_GT] = ACTIONS(35),
    [anon_sym_GT] = ACTIONS(35),
    [anon_sym_PLUS] = ACTIONS(35),
    [anon_sym_DASH] = ACTIONS(35),
    [anon_sym_STAR] = ACTIONS(35),
    [anon_sym_SLASH] = ACTIONS(35),
    [anon_sym_PERCENT] = ACTIONS(35),
    [anon_sym_not] = ACTIONS(35),
    [anon_sym_true] = ACTIONS(35),
    [anon_sym_false] = ACTIONS(35),
    [anon_sym_nil] = ACTIONS(35),
    [sym_string] = ACTIONS(35),
    [sym_number] = ACTIONS(35),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_var] = ACTIONS(15),
    [anon_sym_SEMI] = ACTIONS(15),
    [anon_sym_and] = ACTIONS(15),
    [anon_sym_or] = ACTIONS(15),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(15),
    [anon_sym_EQ_GT] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(25),
    [anon_sym_PERCENT] = ACTIONS(25),
    [anon_sym_not] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_nil] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_var] = ACTIONS(15),
    [anon_sym_SEMI] = ACTIONS(15),
    [anon_sym_and] = ACTIONS(15),
    [anon_sym_or] = ACTIONS(15),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(15),
    [anon_sym_EQ_GT] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_STAR] = ACTIONS(25),
    [anon_sym_SLASH] = ACTIONS(25),
    [anon_sym_PERCENT] = ACTIONS(25),
    [anon_sym_not] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_nil] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_var] = ACTIONS(15),
    [anon_sym_SEMI] = ACTIONS(15),
    [anon_sym_and] = ACTIONS(15),
    [anon_sym_or] = ACTIONS(15),
    [anon_sym_EQ_EQ] = ACTIONS(15),
    [anon_sym_BANG_EQ] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(39),
    [anon_sym_LT_EQ] = ACTIONS(15),
    [anon_sym_EQ_GT] = ACTIONS(15),
    [anon_sym_GT] = ACTIONS(15),
    [anon_sym_PLUS] = ACTIONS(15),
    [anon_sym_DASH] = ACTIONS(15),
    [anon_sym_STAR] = ACTIONS(15),
    [anon_sym_SLASH] = ACTIONS(15),
    [anon_sym_PERCENT] = ACTIONS(15),
    [anon_sym_not] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_nil] = ACTIONS(15),
    [sym_string] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [sym_import] = STATE(18),
    [sym_stmt] = STATE(12),
    [sym_declaration] = STATE(28),
    [sym_expr] = STATE(28),
    [sym_clause] = STATE(27),
    [sym__clause] = STATE(5),
    [sym_binary] = STATE(5),
    [sym_unary] = STATE(5),
    [sym_primary] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(18),
    [aux_sym_source_file_repeat2] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(41),
    [anon_sym_import] = ACTIONS(7),
    [anon_sym_var] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_not] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [anon_sym_nil] = ACTIONS(13),
    [sym_string] = ACTIONS(13),
    [sym_number] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_var,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      sym_clause,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_not,
    STATE(13), 2,
      sym_stmt,
      aux_sym_source_file_repeat2,
    STATE(28), 2,
      sym_declaration,
      sym_expr,
    STATE(5), 4,
      sym__clause,
      sym_binary,
      sym_unary,
      sym_primary,
    ACTIONS(13), 5,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [38] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      anon_sym_var,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    STATE(27), 1,
      sym_clause,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_not,
    STATE(13), 2,
      sym_stmt,
      aux_sym_source_file_repeat2,
    STATE(28), 2,
      sym_declaration,
      sym_expr,
    STATE(5), 4,
      sym__clause,
      sym_binary,
      sym_unary,
      sym_primary,
    ACTIONS(13), 5,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [76] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      anon_sym_var,
    STATE(27), 1,
      sym_clause,
    ACTIONS(50), 2,
      anon_sym_DASH,
      anon_sym_not,
    STATE(13), 2,
      sym_stmt,
      aux_sym_source_file_repeat2,
    STATE(28), 2,
      sym_declaration,
      sym_expr,
    STATE(5), 4,
      sym__clause,
      sym_binary,
      sym_unary,
      sym_primary,
    ACTIONS(53), 5,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [114] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_DOT,
    STATE(15), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(56), 11,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_not,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [137] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      anon_sym_DOT,
    STATE(16), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(60), 11,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_not,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [160] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_DOT,
    STATE(16), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(62), 11,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_not,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [183] = 6,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym_clause,
    STATE(37), 1,
      sym_expr,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_not,
    STATE(5), 4,
      sym__clause,
      sym_binary,
      sym_unary,
      sym_primary,
    ACTIONS(13), 5,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [210] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      anon_sym_import,
    STATE(18), 2,
      sym_import,
      aux_sym_source_file_repeat1,
    ACTIONS(67), 9,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_DASH,
      anon_sym_not,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [232] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 12,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_var,
      anon_sym_EQ,
      anon_sym_DASH,
      anon_sym_not,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
      anon_sym_DOT,
  [250] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_not,
    STATE(8), 4,
      sym__clause,
      sym_binary,
      sym_unary,
      sym_primary,
    ACTIONS(13), 5,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [271] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_not,
    STATE(6), 4,
      sym__clause,
      sym_binary,
      sym_unary,
      sym_primary,
    ACTIONS(13), 5,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [292] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_not,
    STATE(7), 4,
      sym__clause,
      sym_binary,
      sym_unary,
      sym_primary,
    ACTIONS(13), 5,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [313] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_not,
    STATE(3), 4,
      sym__clause,
      sym_binary,
      sym_unary,
      sym_primary,
    ACTIONS(13), 5,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [334] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_not,
    STATE(2), 4,
      sym__clause,
      sym_binary,
      sym_unary,
      sym_primary,
    ACTIONS(13), 5,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [355] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 2,
      anon_sym_DASH,
      anon_sym_not,
    STATE(9), 4,
      sym__clause,
      sym_binary,
      sym_unary,
      sym_primary,
    ACTIONS(13), 5,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [376] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 10,
      ts_builtin_sym_end,
      anon_sym_import,
      anon_sym_var,
      anon_sym_DASH,
      anon_sym_not,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [392] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 10,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_SEMI,
      anon_sym_DASH,
      anon_sym_not,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [408] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 9,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_DASH,
      anon_sym_not,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [423] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 9,
      ts_builtin_sym_end,
      anon_sym_var,
      anon_sym_DASH,
      anon_sym_not,
      anon_sym_true,
      anon_sym_false,
      anon_sym_nil,
      sym_string,
      sym_number,
  [438] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      aux_sym_identifier_token1,
    STATE(26), 1,
      sym_identifier,
  [448] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      aux_sym_identifier_token1,
    STATE(36), 1,
      sym_identifier,
  [458] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      aux_sym_identifier_token1,
  [465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
  [472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      anon_sym_as,
  [479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_unix_path_string,
  [486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      anon_sym_EQ,
  [493] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(92), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 38,
  [SMALL_STATE(13)] = 76,
  [SMALL_STATE(14)] = 114,
  [SMALL_STATE(15)] = 137,
  [SMALL_STATE(16)] = 160,
  [SMALL_STATE(17)] = 183,
  [SMALL_STATE(18)] = 210,
  [SMALL_STATE(19)] = 232,
  [SMALL_STATE(20)] = 250,
  [SMALL_STATE(21)] = 271,
  [SMALL_STATE(22)] = 292,
  [SMALL_STATE(23)] = 313,
  [SMALL_STATE(24)] = 334,
  [SMALL_STATE(25)] = 355,
  [SMALL_STATE(26)] = 376,
  [SMALL_STATE(27)] = 392,
  [SMALL_STATE(28)] = 408,
  [SMALL_STATE(29)] = 423,
  [SMALL_STATE(30)] = 438,
  [SMALL_STATE(31)] = 448,
  [SMALL_STATE(32)] = 458,
  [SMALL_STATE(33)] = 465,
  [SMALL_STATE(34)] = 472,
  [SMALL_STATE(35)] = 479,
  [SMALL_STATE(36)] = 486,
  [SMALL_STATE(37)] = 493,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary, 3, 0, 1),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clause, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary, 3, 0, 1),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(31),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(21),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(4),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 2, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expr, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 5, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [84] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lox(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lox",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
